[tool.poetry]
name = "mcp-explore"
version = "0.1.0"
description = ""
authors = ["fisseha-estifanos <fisseha.137@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
mcp = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
